[package]
name = "advent-of-code-2022"
version = "0.1.0"
authors = ["Sam <samuelkeiffer@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vek = "0.15.4"
itertools = "0.7.8"
